---
driver:
  name: azurerm
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  machine_size: 'Standard_D2_v2'
  location: 'West US 2'

transport:
  name: winrm


provisioner:
  wait_for_retry: 90
  retry_on_exit_code:
    - 35

verifier:
  name: inspec

platforms:
  - name: windows-server-2016
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest

